# Generated by Django 5.0.1 on 2024-01-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_comment_auction'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='cover_image',
            field=models.ImageField(default=None, upload_to='images/'),
            preserve_default=False,
        ),
    ]
