# Generated by Django 5.0.1 on 2024-01-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auction_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='cover_image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
