# Generated by Django 5.0.1 on 2024-01-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_auction_cover_image_auction_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='status',
            field=models.CharField(choices=[('Closed', 'CLOSED'), ('Open', 'OPEN'), ('Deleted', 'DELETED')], default='Open', max_length=32, null=True),
        ),
    ]
